[package]
name = "wow-inventory-sync"
version = "0.2.0"
edition = "2021"

[dependencies]
mlua = {version = "0.8.8", features = ["lua53", "serialize"]}
serde-lua-table = { git = "https://github.com/Nerixyz/serde-lua-table.git", tag = "v0.1.2" }
serde = { version = "1.0.162", features = ["derive"] }
anyhow = "1.0.71"
crossbeam-channel = "0.5.8"
notify = "5.1.0"
tokio = { version = "1.28.0", features = ["full"] }
env_logger = "0.10.0"
log = "0.4.17"
clap = { version = "4.2.7", features = ["cargo"] }
