[package]
name = "wow-inventory-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
mlua = {version = "0.8.1", features = ["lua53", "serialize"]}
serde-lua-table = { git = "https://github.com/Nerixyz/serde-lua-table.git", tag = "v0.1.2" }
serde = { version = "1.0.140", features = ["derive"] }
anyhow = "1"
crossbeam-channel = "0.5.5"
notify = "5.0.0-pre.15"
tokio = { version = "1", features = ["full"] }
env_logger = "^0.9"
log = "0.4"
clap = { version = "^3.2", features = ["derive", "cargo"] }
