[package]
name = "wow-inventory-sync"
version = "0.2.0"
edition = "2021"

[dependencies]
mlua = {version = "0.9.2", features = ["lua53", "serialize"]}
serde-lua-table = { git = "https://github.com/Nerixyz/serde-lua-table.git", tag = "v0.1.2" }
serde = { version = "1.0.193", features = ["derive"] }
anyhow = "1.0.78"
crossbeam-channel = "0.5.10"
notify = "6.1.1"
tokio = { version = "1.35.1", features = ["full"] }
env_logger = "0.10.1"
log = "0.4.20"
clap = { version = "4.4.12", features = ["cargo"] }
