[package]
name = "wow-inventory-sync"
version = "0.2.0"
edition = "2021"

[dependencies]
mlua = {version = "0.9.0", features = ["lua53", "serialize"]}
serde-lua-table = { git = "https://github.com/Nerixyz/serde-lua-table.git", tag = "v0.1.2" }
serde = { version = "1.0.183", features = ["derive"] }
anyhow = "1.0.74"
crossbeam-channel = "0.5.8"
notify = "6.0.1"
tokio = { version = "1.32.0", features = ["full"] }
env_logger = "0.10.0"
log = "0.4.20"
clap = { version = "4.3.22", features = ["cargo"] }
