---
name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ ubuntu ]
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Install lua (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt-get -y install liblua5.3-dev
      - uses: hecrj/setup-rust-action@v2.0.0
      - uses: actions/cache@v3.3.2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo build --release
      - name: Rename release binary
        run: mv target/release/wow-inventory-sync target/release/wow-inventory-sync-linux-x86_64
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          files: |
            target/release/wow-inventory-sync-linux-x86_64
          prerelease: false
